'use client';

import { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { ProductUploadForm, type ProductFormData } from '@/components/admin/ProductUploadForm';
import { OrderManagementTable } from '@/components/admin/OrderManagementTable';
import { useFirestore } from '@/firebase';
import { collection } from 'firebase/firestore';
import { addDocumentNonBlocking } from '@/firebase/non-blocking-updates';
import { useToast } from '@/hooks/use-toast';

// Dummy data as per request
const initialOrders = [
  { id: 'ORD001', total: 2500, status: 'Delivered' },
  { id: 'ORD002', total: 1500, status: 'Pending' },
  { id: 'ORD003', total: 3200, status: 'Delivered' },
  { id: 'ORD004', total: 820, status: 'Pending' },
  { id: 'ORD005', total: 550, status: 'Delivered' },
];

export default function AdminPage() {
  const [orders] = useState(initialOrders);
  const firestore = useFirestore();
  const { toast } = useToast();

  const handleAddProduct = (data: ProductFormData) => {
    if (!firestore) return;
    const productsCollection = collection(firestore, 'products');
    
    // The id will be auto-generated by Firestore, so we can omit it.
    // backend.json defines title, not name.
    const productData = {
      title: data.name,
      description: 'A default product description.', // Assuming a default
      price: data.price,
      categoryId: data.category,
      imageUrl: data.imageUrl,
    };
    
    addDocumentNonBlocking(productsCollection, productData);

    toast({
      title: 'Product Submitted',
      description: `${data.name} is being added to the database.`,
    });
  };

  return (
    <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <h1 className="text-3xl font-bold mb-6">Admin Dashboard</h1>

      <Tabs defaultValue="products">
        <TabsList className="grid w-full grid-cols-2 max-w-md">
          <TabsTrigger value="products">Product Management</TabsTrigger>
          <TabsTrigger value="orders">Order Management</TabsTrigger>
        </TabsList>
        <TabsContent value="products" className="mt-6">
          <Card>
            <CardHeader>
              <CardTitle>Add New Product</CardTitle>
              <CardDescription>Fill out the form below to add a new product to your store.</CardDescription>
            </CardHeader>
            <CardContent>
              <ProductUploadForm onSubmit={handleAddProduct} />
            </CardContent>
          </Card>
        </TabsContent>
        <TabsContent value="orders" className="mt-6">
           <Card>
            <CardHeader>
              <CardTitle>Recent Orders</CardTitle>
              <CardDescription>View and manage customer orders.</CardDescription>
            </CardHeader>
            <CardContent>
               <OrderManagementTable orders={orders} />
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
